/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Dark_Targets.glb 
*/

"use client";

import React from "react";
import { useGLTF } from "@react-three/drei";

import {
  SOFA_PAINTINGS_HITBOX_POSITION,
  SOFA_PAINTINGS_HITBOX_SCALE,
} from "../../sofaPaintingsHitbox";

export default function Model(props) {
  const { nodes } = useGLTF("/models/Dark Room/Dark_Targets.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.About_Hitbox.geometry}
        material={nodes.About_Hitbox.material}
        visible={false}
        position={[0.679, 1.571 - 0.02, -1.368]}
      />
      <mesh
        geometry={nodes.Dev_Work_Hitbox.geometry}
        material={nodes.Dev_Work_Hitbox.material}
        visible={false}
        position={[-0.457, 0.597 - 0.02, 1.021]}
      />
      <mesh
        geometry={nodes.About_Hitbox.geometry}
        material={nodes.About_Hitbox.material}
        visible={false}
        position={SOFA_PAINTINGS_HITBOX_POSITION}
        scale={SOFA_PAINTINGS_HITBOX_SCALE}
      />
    </group>
  );
}

useGLTF.preload("/models/Dark Room/Dark_Targets.glb");
